spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456

mybatis:
   mapperLocations: classpath:/mapper/*.xml
